-- Migration: attendance manual entries (C4) + status-aware calendar (C2)
-- Generated by drizzle-kit, with a data-safety guard prepended.
--
-- Guard: deduplicate attendance rows on (student_id, attendance_date) before
-- adding the UNIQUE index. The prior migration dropped the unique constraint,
-- so duplicate dates may exist from the delete-all+reinsert recalculation era.
-- Keep the most recent row per (student_id, attendance_date); delete older dupes.
DELETE FROM "attendance" a
WHERE a.id NOT IN (
  SELECT DISTINCT ON (student_id, attendance_date) id
  FROM "attendance"
  ORDER BY student_id, attendance_date, created_at DESC, id DESC
);--> statement-breakpoint
ALTER TABLE "attendance" DROP CONSTRAINT "attendance_status_check";--> statement-breakpoint
ALTER TABLE "attendance" ADD COLUMN "recorded_manually" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "students" ADD COLUMN "status_since" date;--> statement-breakpoint
CREATE UNIQUE INDEX "attendance_student_id_attendance_date_key" ON "attendance" USING btree ("student_id","attendance_date");--> statement-breakpoint
ALTER TABLE "attendance" ADD CONSTRAINT "attendance_status_check" CHECK ("attendance"."status" IN ('present', 'absent', 'excused', 'holiday'));--> statement-breakpoint
-- Backfill status_since for existing students: assume current status since enrollment.
UPDATE "students" SET "status_since" = "enrollment_date" WHERE "status_since" IS NULL;